const DummyData = [
  {
    id: 1,
    name: "Elite Haven",
    location: "Bangalore",
    gender: "Girls/Women's",
    roomType: "Single",
    price: 9500,
    rating: 5,
    reviews: 112,
    amenities: ["WiFi", "AC", "Laundry"],
  },
  {
    id: 2,
    name: "Sunrise Stay",
    location: "Mumbai",
    gender: "Men's",
    roomType: "Double",
    price: 6500,
    rating: 4.7,
    reviews: 76,
    amenities: ["WiFi", "Parking", "Meals"],
  },
  {
    id: 3,
    name: "Bliss Co-Living",
    location: "Delhi",
    gender: "Co-Living",
    roomType: "3 Sharing",
    price: 7200,
    rating: 4.5,
    reviews: 89,
    amenities: ["Laundry", "AC", "Gym"],
  },
  {
    id: 4,
    name: "Pearl Nest",
    location: "Hyderabad",
    gender: "Girls/Women's",
    roomType: "Double",
    price: 5800,
    rating: 4.2,
    reviews: 55,
    amenities: ["WiFi", "Housekeeping"],
  },
  {
    id: 5,
    name: "CityView PG",
    location: "Pune",
    gender: "Men's",
    roomType: "4 Sharing",
    price: 4800,
    rating: 1.9,
    reviews: 11,
    amenities: ["WiFi"],
  },
  {
    id: 6,
    name: "Premium Pads",
    location: "Kolkata",
    gender: "Co-Living",
    roomType: "Double",
    price: 7900,
    rating: 4.8,
    reviews: 67,
    amenities: ["WiFi", "Gym", "Laundry"],
  },
  {
    id: 7,
    name: "Cloud 9 Homes",
    location: "Chennai",
    gender: "Girls/Women's",
    roomType: "Single",
    price: 8200,
    rating: 5,
    reviews: 91,
    amenities: ["AC", "WiFi", "Meals"],
  },
  {
    id: 8,
    name: "Zen Men's PG",
    location: "Ahmedabad",
    gender: "Men's",
    roomType: "3 Sharing",
    price: 5600,
    rating: 2.3,
    reviews: 14,
    amenities: ["Laundry", "WiFi"],
  },
  {
    id: 9,
    name: "Horizon Co-Living",
    location: "Bangalore",
    gender: "Co-Living",
    roomType: "Double",
    price: 8800,
    rating: 4.9,
    reviews: 102,
    amenities: ["WiFi", "AC", "Parking"],
  },
  {
    id: 10,
    name: "Shree PG",
    location: "Noida",
    gender: "Girls/Women's",
    roomType: "3 Sharing",
    price: 5100,
    rating: 3.0,
    reviews: 24,
    amenities: ["Meals", "WiFi"],
  },
  {
    id: 11,
    name: "Budget Stay",
    location: "Hyderabad",
    gender: "Men's",
    roomType: "4 Sharing",
    price: 4300,
    rating: 1.5,
    reviews: 8,
    amenities: ["WiFi"],
  },
  {
    id: 12,
    name: "Serene Living",
    location: "Pune",
    gender: "Co-Living",
    roomType: "Single",
    price: 9000,
    rating: 4.6,
    reviews: 60,
    amenities: ["WiFi", "AC", "Laundry"],
  },
  {
    id: 13,
    name: "Garden Girls PG",
    location: "Delhi",
    gender: "Girls/Women's",
    roomType: "Double",
    price: 6000,
    rating: 4.3,
    reviews: 38,
    amenities: ["WiFi", "Laundry"],
  },
  {
    id: 14,
    name: "Classic Men's PG",
    location: "Chennai",
    gender: "Men's",
    roomType: "3 Sharing",
    price: 5200,
    rating: 2.7,
    reviews: 16,
    amenities: ["WiFi", "Meals"],
  },
  {
    id: 15,
    name: "Vista Stay",
    location: "Mumbai",
    gender: "Co-Living",
    roomType: "Double",
    price: 7300,
    rating: 4.4,
    reviews: 49,
    amenities: ["WiFi", "Parking"],
  },
  {
    id: 16,
    name: "Heavenly PG",
    location: "Bangalore",
    gender: "Girls/Women's",
    roomType: "Single",
    price: 9200,
    rating: 5,
    reviews: 130,
    amenities: ["WiFi", "AC", "Laundry", "Meals"],
  },
  {
    id: 17,
    name: "Eco PG",
    location: "Delhi",
    gender: "Men's",
    roomType: "3 Sharing",
    price: 4900,
    rating: 2.2,
    reviews: 13,
    amenities: ["WiFi"],
  },
  {
    id: 18,
    name: "Lake Residency",
    location: "Kolkata",
    gender: "Co-Living",
    roomType: "Double",
    price: 7700,
    rating: 4.1,
    reviews: 42,
    amenities: ["WiFi", "Laundry"],
  },
  {
    id: 19,
    name: "Nest Co-Living",
    location: "Pune",
    gender: "Co-Living",
    roomType: "Single",
    price: 9100,
    rating: 4.9,
    reviews: 80,
    amenities: ["AC", "WiFi", "Gym"],
  },
  {
    id: 20,
    name: "Pink Lotus PG",
    location: "Mumbai",
    gender: "Girls/Women's",
    roomType: "3 Sharing",
    price: 5900,
    rating: 4.0,
    reviews: 30,
    amenities: ["WiFi", "Meals"],
  },
];

export default DummyData;
